name: my_ai_chef
description: "A new Flutter project."

# Prevent the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs to work.
dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.7
  cupertino_icons: ^1.0.8 # Adds the Cupertino Icons font
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Recommended lints for good coding practices

# Information on the generic Dart part of this file can be found at:
# https://dart.dev/tools/pub/pubspec

# Flutter-specific section.
flutter:
  uses-material-design: true # Ensures Material Icons are included

  # To add assets to your application, include an assets section:
  assets:
    - assets/Logo.png

  # For details on adding assets from package dependencies, see:
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts, include a fonts section here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details on fonts from package dependencies, see:
  # https://flutter.dev/to/font-from-package
